### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [warprince27/prj-rev-bwfs-dasmoto#4]
Overall, great job on your project. Your solution code looks great and your webpage looks on point. Both of your files were indented properly and I like the comments you had in your HTML. Nice job adding wrapping divs on your HTML elements. Good job putting styles on elements. Remember to set your `font-family` on an overarching element and to set alt tags. All in all, fantastic job.

**Comment by warprince27** [comment]
thanks for the feedback, had fun doing this - I have made the recommendations and will aim to do this for the future projects
